In [ ]:
class crop:
  def __init__(self,name,season,expected_yield):
    self.name=name
    self.season=season
    self.expected_yield=expected_yield
rice=crop("rice","kharif",5.2)
wheat=crop("wheat","rabi",4.1)
print(rice.name,rice.season,rice.expected_yield)
print(wheat.name,wheat.season,wheat.expected_yield)

rice kharif 5.2
wheat rabi 4.1


In [ ]:
class crop:
  def __init__(self,name,season,expected_yield):
    self.name=name
    self.season=season
    self.expected_yield=expected_yield

  def total_production(self,area):
    return self.expected_yield*area

area=10
rice=crop("rice","kharif",5.2)
print("total rice production:", rice.total_production(area),"tones")

total rice production: 52.0 tones


In [ ]:
class crop:
  def __init__(self,name,season,expected_yield):
    self.name=name
    self.season=season
    self.expected_yield=expected_yield

  def total_production(self,area):
    return self.expected_yield*area

rice=crop("rice","khari",5.2)
wheat=crop("wheat","rabi",4.1)
corn=crop("corn","kharif",6.8)
cotton=crop("cotton","kharif",22.3)
all_crops=[rice,wheat,corn,cotton] # Renamed list for clarity
for current_crop in all_crops: # Corrected variable name and iterated list
  production=current_crop.total_production(10) # Corrected method call
  print(f"{current_crop.name}:{production}tons")

rice:52.0tons
wheat:41.0tons
corn:68.0tons
cotton:223.0tons


In [ ]:
#traditional python list
temp_list=[36,37,40,48,33,28,32]
#covert to numpy array
import numpy as np
temps_array=np.array([32,37,40,48,33,28,32])
print(temps_array)

[32 37 40 48 33 28 32]


In [ ]:
#temperatures from 3 sensorsover 5 days
sensor_temps=np.array([
    [33,37,35],#day1
    [40,44,28],#day2
    [44,45,35],#day3
    [41,38,36],#day4
    [36,39,35],#day5
])
print(sensor_temps)
print(f"shape:{sensor_temps.shape}")


[[33 37 35]
 [40 44 28]
 [44 45 35]
 [41 38 36]
 [36 39 35]]
shape:(5, 3)


In [ ]:
#array of zeros(5*3)
zeros=np.zeros((5,3))
#array of ones(5*3)
ones=np.ones((5,3))
#identity matrix(3*3)
identity=np.eye((3))
#range of values
sequence=np.arange(0,1,0.2)
#evenly spaced values
linspace=np.linspace(0,100,5)
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np
# ndim:number of dimensions
arr = np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [ ]:
import numpy as np
#shape=dimention size
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [ ]:
import numpy as np
#size=total element
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [ ]:
import numpy as np
#dtype:data type
arr=np.array([1.5,2.7,3.5])
print(arr.dtype)

float64


In [ ]:
import numpy as np
#itemsize:bytes per element
print(arr.itemsize)

8


In [ ]:
crop=np.array(['corn','wheat','soya','barley','oats'])
#accesss single element(zero indexed)
print (crop[0])
print(crop[-1])
#access multiple elements
print(crop[1:4])
print(crop[1:2])

corn
oats
['wheat' 'soya' 'barley']
['wheat']


In [2]:
import numpy as np
#soil ph readings(3fields *4samples)
ph_levels=np.array([
    [6.5,6.8,6.3,6.7],
    [7.1,7.0,6.9,7.2],
    [6.2,6.4,6.1,6.3]
])
#for single element:row 1,column 2
print(ph_levels[1,2])
#entire row 0
print(ph_levels[0,:])
#entire column 3
print(ph_levels[:,3])

6.9
[6.5 6.8 6.3 6.7]
[6.7 7.2 6.3]


In [3]:
temperature=np.array([72,85,91,68,95,70,88])
#creat a boolean array(mask)
hot_days=temperature>85
print (hot_days)

[False False  True False  True False  True]


In [4]:
#use mask to filter original array
print (temperature [hot_days])

[91 95 88]


In [5]:
#can do it in one line
print(temperature[temperature>85])

[91 95 88]


In [6]:
#crop yield in tons
field_a =np.array([120,135,142,128])
field_b=np.array([118,140,138,132])
#add arrays
total_yield=field_a+field_b
print(total_yield)


[238 275 280 260]


In [7]:
#substract to find difference
difference =field_a-field_b
print(difference)

[ 2 -5  4 -4]


In [8]:
#multiply each by constant
doubled=field_a*2
print(doubled)

[240 270 284 256]


In [9]:
#python list approach(slow!)
result=[]
for i in range(len(field_a)):
  result.append(field_a[i]+field_b[i])
  print (result)

[np.int64(238)]
[np.int64(238), np.int64(275)]
[np.int64(238), np.int64(275), np.int64(280)]
[np.int64(238), np.int64(275), np.int64(280), np.int64(260)]
